# Site settings
title: SciTech
subtitle: "Science Automation Technologies"

exclude:
  - .jekyll-cache
  - .idea
  - README.md
  - LICENSE

# scholar
scholar:
  sort_by: author
  group_by: year
  group_order: descending
  type_order: [article, inproceedings, phdthesis, techreport]
  bibliography_template: bib
  reference_template: bib

plugins:
  - jekyll-scholar
